### PR TITLE
Implement spinwheel & RNG feedback

### PR DESCRIPTION
**Pull request by LBBO**
- Rename "Namen auslosen" to "Begriffe auslosen"
- Add all of the lists in the spinwheel to the state, which means persistence between opened instances & exports
- Add option to draw fresh options
- Play sound effect while wheel is still spinning (⚠️  @liam-k: you still need to find a proper sound for this!)

**Reviewer's task:**

- [ ] I didn't see no code smells
- [ ] The live preview works as expected -> no regressions found

### CODE REVIEW

**Comment by liam-k** [comment]
Thanks! Seems to work well – one thing though: The "don’t repeat options" thing could be kind of confusing I think, because it just starts over after all options have been selected once. Could we have some kind of indicator? 

Maybe we can just rename the "Drehen" button to "Drehen (neuer Durchlauf)" or similar after all options have been called once (& at the start of course, if "don’t repeat" is enabled).

Also, we should rename "Zahlen 1-8" to "Zahlen" now.

**Comment by LBBO** [comment]
It's no different with "Begriffe auslosen" tho

**Comment by liam-k** [comment]
> It's no different with "Begriffe auslosen" tho

Yeah, but there we have visual feedback so you intuitively know it’s over. Maybe that could work for the spinwheel too, just remove names we already had? (just make sure they stay in the textbox tho)

image

**Comment by LBBO** [comment]
done

**Pull request merged**
